export enum StepType {
    RECEIVE_DIVINE_BLESSINGS = 0,
    CALL_FOR_REINFORCEMENTS = 1,
    SELECT_ACTION_TO_PERFORM = 2,
    MAKE_OFFERING_TO_GODS = 3,
    PERFORM_HEROIC_FEAT = 4,
    SELECT_EXTRA_ACTION_TO_PERFORM = 5,
    ROLL_ALL_HEROES_DICE = 6,
    ROLL_HERO_BOTH_DICE = 7,
    ROLL_SINGLE_DIE = 8,
    APPLY_DIE_FACE_EFFECTS = 9,
}