export enum StepType {
    RECEIVE_DIVINE_BLESSINGS = 0,
    CALL_FOR_REINFORCEMENTS = 1,
    PERFORM_ACTION = 2,
    PERFORM_EXTRA_ACTION = 3,
    ROLL_ALL_HEROES_DICE = 4,
    ROLL_HERO_BOTH_DICE = 5,
    ROLL_SINGLE_DIE = 6,
    APPLY_DIE_FACE_EFFECTS = 7,
}