export enum StepType {
    RECEIVE_DIVINE_BLESSINGS = 0,
    RECEIVE_DIVINE_BLESSING = 1,
    CALL_FOR_REINFORCEMENTS = 2,
    SELECT_ACTION_TO_PERFORM = 3,
    MAKE_OFFERING_TO_GODS = 4,
    PERFORM_HEROIC_FEAT = 5,
    SELECT_EXTRA_ACTION_TO_PERFORM = 6,
    ROLL_ALL_HEROES_DICE = 7,
    ROLL_HERO_BOTH_DICE = 8,
    ROLL_SINGLE_DIE = 9,
    APPLY_DIE_FACE_EFFECTS = 10
}